Fix test error caused by using RAILS_ROOT
Fixes the following test error:

    4) Error:
  test_should_have_default_migration_dir_set(MigrationTestHelperTest):
  NameError: uninitialized constant MigrationTestHelperTest::RAILS_ROOT
      /test/migration_test_helper_test.rb:244:in `test_should_have_default_migration_dir_set'